### ISSUE TITLE
[Feature Request] Trinkets support

### ISSUE THREAD

**Issue by Bazyliii** [SLH335/netherite-extras#1]
As in title, optional trinkets support would be nice. It should work just like in Charm of Undying mod.

**Comment by SLH335** [comment]
That's a good idea! I'll look into adding support for Trinkets.

**Comment by peow** [comment]
an update: charm of undying added support to totem of neverdying

**Comment by SLH335** [comment]
Sorry, I haven't really had time to work on this mod recently. But it seems like it was more sensible to implement this in Charm of Undying anyway, as Trinket support for the Totem of Neverdying should probably only work if you have Charm of Undying installed as well. It looks like everything works correctly on their side, so I will close this issue.
