### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by mikaba-eu** [SLH335/netherite-extras#4]
Hallo SLH335,

ich bin auf der suche nach einem Modder, der ggf lust hätte bei uns im Projekt mit zu machen.
Aktuell bin ich der einzige Entwickler und vllt. sagt dir das Projekt ja zu, würde mich freuen, wenn du mich mal auf Discord anschreibst.

Discord: maybe_mika
Projekt Webseite: https://gearcraft.org

LG

**Comment by SLH335** [comment]
Hallo dakiba,

im Moment habe ich keine Zeit an deinem Projekt mitzuarbeiten, deswegen muss ich leider ablehnen. Ich wünsche dir aber viel Erfolg dabei!
