### ISSUE TITLE
[Feature Request] Configurable Netherite Nugget drop chance

### ISSUE THREAD

**Issue by Proxi2** [SLH335/netherite-extras#6]
It would be nice to have a config file so I could disable piglin brutes dropping netherite nuggets. I do think that it’s balanced normally, but in my modpack I have a mod that adds piglin brute spawners, so it makes it pretty op

**Comment by SLH335** [comment]
Thanks for the suggestion. I agree, that would be a nice feature. I have added a config file with an option to customize the drop chance from 0% to 100%. The config works with ModMenu as well, but you have to rejoin the world for the change to take effect. The feature will be included in the next release, I'll upload it in a few hours.
