### ISSUE TITLE
Fresh Animations Extensions Compatibility

### ISSUE THREAD

**Issue by Proxi2** [SLH335/netherite-extras#7]
Hey I made a resource pack that remakes the netherite horse armor texture to be compatible with the [Fresh Animations Classic Horses Extension](https://modrinth.com/resourcepack/fresh-animations-extensions) I use. I was able to do most of it by just moving around textures and only had to do a little bit of pixel painting. I was wondering if you'd like me to send you the pack so that you could post it on Modrinth. Or if you don't want to, would be okay for me to post it and use your armor item png as the project icon and pack.png. I'd keep it unlisted and let you look the page over to make sure you're happy with everything before I set it to public

Before
![2024-08-16_08 47 01](https://github.com/user-attachments/assets/be6e89bd-803a-437b-9958-21dd9181d2c4)

After
![2024-08-16_08 47 14](https://github.com/user-attachments/assets/f9e89fb6-e2ea-44ed-a02b-e535e3f6e0ac)

**Comment by SLH335** [comment]
Hi, thank you for your contribution! I'd be happy to publish the pack on Modrinth as the official Netherite Extras compatibility pack with _Fresh Animations Extensions_, if you want me to.

**Comment by Proxi2** [comment]
Absolutely :) 
[Netherite Horse Armor + FA-Extensions.zip](https://github.com/user-attachments/files/16641274/Netherite.Horse.Armor.%2B.FA-Extensions.zip)
Feel free to change the pack.mcmeta and pack.png to whatever you like. I just have those in there as placeholders. I'm really glad I could contribute something my server mates and I absolutely adore this mod. In the future I plan on adding animations like blinking on the Totem of Neverdying and matte glint on both of the apple textures to match other animated textures we use from packs like Animated Items

**Comment by SLH335** [comment]
Hi, sorry, I've been a bit inactive recently. I've made a few tweaks to the neck portion of the texture. Are you ok with these changes?

![2024-09-06_20 00 14](https://github.com/user-attachments/assets/0f5ed582-2450-4c0b-8490-703d2ec99bee)

Netherite Extras and its assets are licensed under the [GPL v3.0](https://www.gnu.org/licenses/gpl-3.0.en.html). Are you ok with the compatibility pack being licensed like that as well?

I am ready to publish the Modrinth page if you are ok with everything.

**Comment by Proxi2** [comment]
No worries. I think the updated texture looks great, and have no problem with you posting it under that license. Go right ahead :)

**Comment by SLH335** [comment]
Alright, the pack is now available [here](https://modrinth.com/resourcepack/netherite-extras-x-fresh-animations-extensions).
I've also invited you to the project on Modrinth (assuming you are [proxi](https://modrinth.com/user/proxi))

**Comment by Proxi2** [comment]
Thanks for adding me! And great job on the description. I only have 2 small things to add.

The pack in game shows up without an icon. It looks like you named it icon.png instead of pack.png. 
![image](https://github.com/user-attachments/assets/c19f2427-461d-4f62-b173-13f840b866ff)
I went and renamed it to pack.png and it works fine so it looks like that's all you need to do there.
![image](https://github.com/user-attachments/assets/8cf5f7db-77ae-45e2-8aea-94c727f4a49f)

The other thing is that I would add is something clarifying that the pack must be placed above FA-Extensions in the resource pack list to work in game. Most packs do that. Here's a screenshot from the resource pack screen that you can add to the description (and the gallery?) so you don't have to go grab one yourself
![image](https://github.com/user-attachments/assets/3a75e6e3-8465-4aaa-b7e2-a088504e0c65)

Other than those two honestly quite minor things it looks good. Happy to have it on Modrinth finally 😁

**Comment by SLH335** [comment]
Thanks! Right, forgot to rename the icon, I just copied it directly from the mod. I've published a new version and added some instructions to the page, thanks for the screenshot.

**Comment by Proxi2** [comment]
Everything looks good!
